name: flutter_qiita_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.5.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  retrofit: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  retrofit_generator: ^8.1.0
  build_runner: ^2.4.10
  json_serializable: ^6.8.0
  freezed: ^2.5.2
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  flutter_gen_runner: ^5.5.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/

flutter_gen:
  integrations:
    flutter_svg: true